### ISSUE TITLE
crash with jei compat

### ISSUE THREAD

**Issue by meelock** [TheRActivator/From-the-Ground-Up#14]
In short, i opened the research table, and the game froze so that i had to force quit it.

the error in short was:
[17:58:17] [Netty Local Client IO #0/ERROR] [FML]: SimpleChannelHandlerWrapper exception
java.lang.NoSuchMethodError: mezz.jei.Internal.getRuntime()Lmezz/jei/JeiRuntime;
	at ftgumod.compat.CompatJEI.run(CompatJEI.java:54) ~[CompatJEI.class:?]
	at ftgumod.FTGU.runCompat(FTGU.java:70) ~[FTGU.class:?]
	at ftgumod.packet.client.TechnologyMessage$TechnologyMessageHandler.handleClientMessage(TechnologyMessage.java:74) ~[TechnologyMessage$TechnologyMessageHandler.class:?]
	at ftgumod.packet.client.TechnologyMessage$TechnologyMessageHandler.handleClientMessage(TechnologyMessage.java:62) ~[TechnologyMessage$TechnologyMessageHandler.class:?]
	at ftgumod.packet.MessageHandler.onMessage(MessageHandler.java:21) ~[MessageHandler.class:?]

The full log: [HERE](http://paste.ubuntu.com/24423881/)

**Comment by Astavie** [comment]
Yeah I was afraid something like this might happen... What version of Minecraft and JEI are you using?

**Comment by Astavie** [comment]
Right - found out I was using an outdated version of JEI. Should be easy to fix
