### ISSUE TITLE
Internal server error when eating food with effect 

### ISSUE THREAD

**Issue by hookBG** [TheRActivator/From-the-Ground-Up#55]
details
`[18:23:11] [Server thread/WARN] [net.minecraft.network.NetworkSystem]: Failed to handle packet for /PLAYER_IP
net.minecraft.util.ReportedException: Ticking player
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:459) ~[oq.class:?]
	at net.minecraft.network.NetHandlerPlayServer.redirect$onPlayerTick$zio000(NetHandlerPlayServer.java:2050) ~[pa.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173) ~[pa.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) ~[NetworkDispatcher$1.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) ~[gw.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [oz.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_192]
Caused by: java.lang.IllegalStateException: progressMap isn't initialized
	at com.google.common.base.Preconditions.checkState(Preconditions.java:444) ~[minecraft_server.1.12.2.jar:?]
	at net.minecraft.advancements.AdvancementProgress.getProgressMap(SourceFile:626) ~[k.class:?]
	at net.minecraft.advancements.AdvancementProgress.invalidateAchievedState(SourceFile:803) ~[k.class:?]
	at net.minecraft.advancements.CriterionProgress.handler$onObtain$zba000(SourceFile:562) ~[o.class:?]
	at net.minecraft.advancements.CriterionProgress.func_192153_b(SourceFile:29) ~[o.class:?]
	at net.minecraft.advancements.AdvancementProgress.spongeGrantCriterion(SourceFile:688) ~[k.class:?]
	at net.minecraft.advancements.AdvancementProgress.handler$onGrantCriterion$zzm000(SourceFile:679) ~[k.class:?]
	at net.minecraft.advancements.AdvancementProgress.func_192109_a(SourceFile) ~[k.class:?]
	at ftgumod.technology.Technology.grantCriterion(Technology.java:289) ~[Technology.class:?]
	at ftgumod.util.ListenerTechnology.func_192159_a(ListenerTechnology.java:28) ~[ListenerTechnology.class:?]
	at net.minecraft.advancements.critereon.EffectsChangedTrigger$Listeners.func_193432_a(SourceFile:110) ~[ae$a.class:?]
	at net.minecraft.advancements.critereon.EffectsChangedTrigger.func_193153_a(SourceFile:61) ~[ae.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_70670_a(EntityPlayerMP.java:1195) ~[oq.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70690_d(EntityLivingBase.java:748) ~[vp.class:?]
	at net.minecraft.item.ItemAppleGold.func_77849_c(SourceFile:39) ~[aik.class:?]
	at net.minecraft.item.ItemFood.func_77654_b(SourceFile:46) ~[aij.class:?]
	at net.minecraft.item.ItemStack.func_77950_b(ItemStack.java:222) ~[aip.class:?]
	at net.minecraft.entity.EntityLivingBase.func_71036_o(EntityLivingBase.java:2781) ~[vp.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_71036_o(EntityPlayerMP.java:1125) ~[oq.class:?]
	at net.minecraft.entity.EntityLivingBase.func_184608_ct(EntityLivingBase.java:2680) ~[vp.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2090) ~[vp.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234) ~[aed.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382) ~[oq.class:?]
	... 10 more
[18:23:11] [Server thread/INFO] [net.minecraft.network.NetHandlerPlayServer]: joke lost connection: Internal server error
[18:23:11] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: joke left the game`

**Comment by hookBG** [comment]
sponge server
